// src/component/MatrixItem/MatrixItem.vue
<style src="./MatrixItem.scss" module lang="scss">
</style>
<script src="./MatrixItem.js">
</script>

<template>
  <Dial
    :size="80"
    :min="dialData.min"
    :max="dialData.max"
    :integer="dialData.integer"
    :value="value"
    :formatter="dialData.formatter"
    style="margin: 0 auto"
    @change="onValueChange"
  />
</template>

// src/components/matrix-item/MatrixItem.tsx
import { Dial } from "@/src/components/dial/Dial";
import { useMatrixStore } from "@/src/data/matrixStore";
import { MatrixItem } from "@/src/types/matrix.types";

type Props = {
  matrixItem: MatrixItem;
};
const DIAL_SIZE = 130;
const DIAL_BUTTON_SIZE = 100;

export function MatrixItem({ matrixItem }: Props) {
  const { setValue, editMode } = useMatrixStore();

  const matrixItemValue = matrixItem[editMode];

  if (matrixItemValue.type === "number") {
    return (
      <Dial
        min={matrixItemValue.min}
        max={matrixItemValue.max}
        value={matrixItemValue.value}
        onChange={(value) => setValue(editMode, matrixItem.index, value)}
        size={DIAL_SIZE}
        buttonSize={DIAL_BUTTON_SIZE}
        integer={matrixItemValue.isInteger}
      />
    );
  }
}
