// src/component/Matrix/Matrix.vue
<style src="./Matrix.scss" module lang="scss">
</style>
<script src="./Matrix.js">
</script>

<template>
  <div>
    <div
      v-for="(row, index) in matrix.rows"
      :key="index"
      :class="$style.row"
    >
      <div
        v-for="item in row"
        :key="`${item.position.x}-${item.position.y}`"
        :class="[$style.rowItem, itemIsActive(item) ? $style.active : null]"
      >
        <MatrixItem :matrix-item="item" />
      </div>
      <div :class="[$style.rowItem, $style.rowGroupItem]">
        <MatrixGroupItem :matrix-items="row"/>
      </div>
    </div>
    <div :class="$style.row">
      <div
        v-for="(column, index) in matrix.columns"
        :key="index"
        :class="[$style.rowItem, $style.columnGroupItem]"
      >
        <MatrixGroupItem :matrix-items="column"/>
      </div>
    </div>
  </div>
</template>

// src/components/matrix/Matrix.tsx
import { MatrixItem } from "@/src/components/matrix-item/MatrixItem";
import { useMatrixStore } from "@/src/data/matrixStore";
import {
  StyledMatrixRow,
  StyledMatrixWrapper,
} from "@/src/components/matrix/Matrix.styles";

export function Matrix() {
  const { matrix } = useMatrixStore();

  return (
    <StyledMatrixWrapper>
      {Array.from({ length: matrix.rows }).map((_, index) => {
        const startIndex = index * matrix.columns;
        const endIndex = startIndex + matrix.columns;
        const rowItems = matrix.items.slice(startIndex, endIndex);
        return (
          <StyledMatrixRow key={index}>
            {rowItems.map((item, index) => {
              return <MatrixItem matrixItem={item} key={index} />;
            })}
          </StyledMatrixRow>
        );
      })}
    </StyledMatrixWrapper>
  );
}
