// src/component/Transport/Transport.vue
<style src="./Transport.scss" module lang="scss"></style>
<script src="./Transport.js"></script>

<template>
  <div :class="$style.transport">
    <div :class="$style.time">
      0.0s
    </div>
    <div :class="$style.bpm">
      120bpm
    </div>
    <div :class="$style.playstop">
      <button @click="start">start</button>
      <button @click="stop">stop</button>
    </div>
  </div>
</template>

// src/components/transport/Transport.tsx
import { useInterval } from "usehooks-ts";
import { usePlayTime } from "@/src/utils/hooks/usePlayTime";
import { useIsPlaying } from "@/src/utils/hooks/useIsPlaying";
import { soundManager } from "@/src/sound/SoundManager";
import { usePlayStore } from "@/src/data/playStore";

export function Transport() {
  const { bpm } = usePlayStore();
  const playTime = usePlayTime();
  const isPlaying = useIsPlaying();

  useInterval(() => {}, 0);

  return (
    <>
      <h2>{playTime.toFixed(1)}</h2>
      <h3>{bpm}</h3>
      <div>
        <button
          onClick={() => {
            if (isPlaying) {
              soundManager.stop();
            } else {
              soundManager.start();
            }
          }}
        >
          {isPlaying ? "Stop" : "Start"}
        </button>
      </div>
    </>
  );
}
